name: CD‑Staging (Ionic/Angular)

on:
  push:
    branches: [ staging ]       # any merge into staging

env:                            # shared
  AWS_REGION: us-east-1
  ECR_REGISTRY: 123456789012.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_NAME: yap-frontend

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: Staging        # optional reviewer
    outputs:
      image: ${{ steps.meta.outputs.image }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Build Ionic production bundle
      - run: npm ci
      - run: npm run build       # ionic build --prod

      # Login & push container (multi‑stage Dockerfile serves www/ via nginx)
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Build & push image
        id: meta
        run: |
          IMAGE="$ECR_REGISTRY/$IMAGE_NAME:${GITHUB_SHA::8}"
          docker build -t "$IMAGE" -f docker/Dockerfile .
          docker push "$IMAGE"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      # Deploy to EKS (staging namespace)
      - name: Configure kubectl
        run: aws eks update-kubeconfig --name yap-frontend-staging --region $AWS_REGION

      - name: Rollout image
        run: |
          kubectl set image deployment/frontend deployment=$IMAGE --record
          kubectl rollout status deployment/frontend

      # Smoke test frontend endpoint
      - name: Smoke test
        run: curl -f http://frontend.staging.svc.cluster.local/health || exit 1

  promote:
    needs: build-deploy
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Promote staging → production branch
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}          # PAT (repo scope)
          commit-message: "Promote staging → production (${GITHUB_SHA::8})"
          base: production
          branch: staging
          title: "Release ${GITHUB_SHA::8} to production"
            body: |
                This PR promotes the latest staging build to production.
                It was automatically generated by GitHub Actions.
                Please review and merge it to deploy the changes.